[tool.poetry]
name = "inspectds"
version = "0.1.0"
description = ""
authors = ["Panos Mavrogiorgos <pmav99@gmail.com>"]

[tool.poetry.scripts]
inspectds = "inspectds.cli:app"

[tool.poetry.dependencies]
python = "^3.7"
xarray = "^0.16"
zarr = "^2.8"
typer = "^0.3"
netCDF4 = "^1.5"
cfgrib = { version = "^0.9", optional = true }

[tool.poetry.extras]
grib = ["cfgrib"]

[tool.poetry.group.dev.dependencies]
pytest = "^6.2"
pytest-cov = "^2.12"
black = "^21.9b0"
reorder-python-imports = "^2.5"
mypy = "^0.812"
prospector = {version = "^1.3", extras = ["all"]}
pre-commit = "^2.13"
conda-lock = "^0.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py37']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --verbose --showlocals --tb=short --cov=inspectds --cov-report term-missing"
testpaths = [
    "tests",
]
